name: Check migrations
on:
  pull_request:
    paths:
      - 'database/migrations/**'

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: juan-castillo-housfy
          minimum-approvals: 1
