name: Check migrations
on:
  pull_request_review:
    types: [submitted]
    paths:
      - 'database/migrations/**'

permissions:
  issues: write
  pull-requests: write

jobs:
  #  Running directly on hosts
  verifyReviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: housfy/verify-users-approval@v1.0.18
        id: verify_reviewers
        with:
          pullnumber: ${{ github.event.pull_request.number }}
          users: juan-castillo-housfy,roger-sole-housfy
          minreviewers: 1
        env:
          GITHUB_TOKEN: ${{ github.token }}
