name: Check migrations
on:
  pull_request:
    paths:
      - 'database/migrations/**'

permissions:
  issues: write
  pull-requests: write

jobs:
  verifyReviwers:
    runs-on: ubuntu-latest
    steps:
      - uses: jesus-ortega-housfy/verify-users-approval@v1.0.9
        id: verify users
        with:
          pullnumber: ${{ github.event.pull_request.number }}
          users: juan-castillo-housfy,roger-sole-housfy
          minreviewers: 1
        env:
          GITHUB_TOKEN: ${{ github.token }}
