name: Check migrations
on:
  pull_request:
    paths:
      - 'database/migrations/**'

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_reviews
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}/reviews
          owner: jesus-ortega-housfy
          repo: example-app
          pull_number: ${{github.event.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_reviews.outputs.data }}"

#    This cannot be used because it does not provide the list of people that have approved the PR
#    if: ${{ (github.event.review.state == 'approved') && (contains(github.event.pull_request.labels.*.name, 'test')) }}
#    steps:
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJSON(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - run: echo ${{ github.event.review.state }}

#    Cannot use this because it "pauses" the build and as a result
#    runs-on: ubuntu-latest
#    steps:
#      - uses: trstringer/manual-approval@v1
#        with:
#          secret: ${{ github.TOKEN }}
#          approvers: juan-castillo-housfy
#          minimum-approvals: 1
